### PR TITLE
Submodules 'n Presets

### PR DESCRIPTION
**Pull request by koxx12-dev**
Moved every repo dependency besides luau to a submodule (tldr: repo in a repo)
Added cmake presets for more consistent devex between editors
Updated CI to use above mentioned presets

I would recommend soft forking luau at a later date and also making it a submodule

### CODE REVIEW

**Comment by SecondNewtonLaw** [comment]
This is not possible, some dependencies have been purposely modified from upstream, thus this cannot be done.

~~It would also increase the complexity more than it already is, not willing when this is not a looked at project~~

**Comment by koxx12-dev** [comment]
what dependencies? only luau seems to be modified

**Comment by SecondNewtonLaw** [comment]
> what dependencies? only luau seems to be modified

some libraries have been modified to be statically linked

**Comment by koxx12-dev** [comment]
i have no idea what you are talking about, it works perfectly fine.
im assuming settings triplets manually statically links every library needed

**Comment by SecondNewtonLaw** [comment]
> i have no idea what you are talking about, it works perfectly fine. im assuming settings triplets manually statically links every library needed

Even if it did; I don't wish for the project to be splitted across many repositories, makes it more cumbersome to develop either way. I will only make a submodule architecture when I see it fit, and I don't see it fit currently, there is no reason to increase complexity that way, and libraries *have* been modified since I have used this old project template of mine before and I know that some dependencies are modified aside from Luau

**Comment by koxx12-dev** [comment]
ah, understandable i will make another commit with just presets

**Comment by SecondNewtonLaw** [comment]
> ah, understandable i will make another commit with just presets

G then bro, ty for contributing, though

**Pull request closed without merging**
