### PR TITLE
CMake Presets

### PR DESCRIPTION
**Pull request by koxx12-dev**
Provides a more streamlined devex by providing a standardized config and build setup
BUT
Requires setting VCPKG_ROOT environment variable locally on developers machine

also uses separate build folders for every preset including default

### CODE REVIEW

**Comment by Pixeluted** [comment]
Did you test this?

**Comment by koxx12-dev** [comment]
it builds, no idea what you want more

**Comment by Pixeluted** [comment]
Where do you set the vcpkg root

**Comment by koxx12-dev** [comment]
windows settings, since you cant modify environment variables for presets

**Comment by Pixeluted** [comment]
idk if i will merge this

**Comment by koxx12-dev** [comment]
for presets there is either this or setting toolchain directly 🤷  no way around it
also its like a once time set it and forget it type of thing

**Comment by koxx12-dev** [comment]
bump

**Pull request merged**
