### PR TITLE
Remove dependencies for proprietary fool projects (Themida, obfus.h, and oxorany)

### PR DESCRIPTION
**Pull request by DataM0del**
No use if it's Open Source anyways.

### CODE REVIEW

**Comment by Pixeluted** [comment]
Doesn't matter, it will not get compiled to the build because it's not used.

**Comment by DataM0del** [comment]
> Doesn't matter, it will not get compiled to the build because it's not used.

What's the point of it being there if it's not used? To waste disk space or something (I mean it's gonna be in git so it wastes disk space anyways unless you do a shallow clone I think)?

**Comment by DataM0del** [comment]
> Doesn't matter, it will not get compiled to the build because it's not used.

Also, unrelated but I would like to add that your bandage fixes in 55ce9bcad92582fa2a36cab8fb83fdcac3b01215 seem to break RbxStu, I haven't fully tested, but removing that seems to make it not print exceptions every 1 minute or so. Probably should remove it.

**Comment by Pixeluted** [comment]
That's only because I didn't update it blud, should I update it?

**Comment by DataM0del** [comment]
> That's only because I didn't update it blud, should I update it?

Probably. Or just make the signature yourself lol... Also, if it works without the bandage fix, it probably shouldn't be there because it's a useless fix if it works without it.

**Comment by Pixeluted** [comment]
It doesn't work without the fix, because you won't be able re-initialize after leaving play session + I cannot make it signature bc the signature maker crashes on that function and I've already reported that on their github as issue and they didn't fix it

**Comment by DataM0del** [comment]
> It doesn't work without the fix, because you won't be able re-initialize after leaving play session + I cannot make it signature bc the signature maker crashes on that function and I've already reported that on their github as issue and they didn't fix it

Oh. :skull:
Probably should use a different signature maker? [Found one written in Rust](https://github.com/unknowntrojan/binja_coolsigmaker) if that helps.

**Comment by Pixeluted** [comment]
The offset didn't need updating, everything works fine for me, I will just add another blocked service

**Comment by Pixeluted** [comment]
> Doesn't matter, it will not get compiled to the build because it's not used.

**Comment by DataM0del** [comment]
Ok :yawning_face:

**Pull request closed without merging**
